### ISSUE TITLE
Readme link not publicly accessible

### ISSUE THREAD

**Issue by bbrandt** [cognitedata/python-oidc-authentication#6]
The [How to get started with Native Tokens in AAD Complete all 4 steps here (including the experimental part)](https://cognitedata.atlassian.net/wiki/spaces/AUTH/pages/1955397887/How+to+get+started+with+Native+Tokens+in+AAD) link in readme.md does not seem to lead to a page that people outside of Cognite can access. Is there publicly accessible documentation this can reference instead?  Thanks!

**Comment by muradsater** [comment]
Solved
